# ── Interfaz y protocolo ─────────────────────────────────────
listen=YES
listen_ipv6=NO

# ── Autenticación ────────────────────────────────────────────
anonymous_enable=NO
local_enable=YES
write_enable=YES
local_umask=022

# ── Jail (chroot) ─────────────────────────────────────────────
# El usuario queda enjaulado en su directorio home (/srv/ftp/shared)
chroot_local_user=YES
allow_writeable_chroot=YES

# ── Modo pasivo ──────────────────────────────────────────────
# pasv_addr_resolve=YES hace que vsftpd resuelva el hostname en runtime
pasv_enable=YES
pasv_addr_resolve=YES
pasv_address=ftp_jail
pasv_min_port=21100
pasv_max_port=21110

# ── Logging ───────────────────────────────────────────────────
xferlog_enable=YES
xferlog_std_format=YES
log_ftp_protocol=YES

# ── Seguridad ────────────────────────────────────────────────
secure_chroot_dir=/var/run/vsftpd/empty
pam_service_name=vsftpd