apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f wordpress-kubernetes.yml --out ./kubernetes/
    kompose.version: 1.38.0 (a8f5d1cbd)
  labels:
    io.kompose.service: dns
  name: dns
spec:
  ports:
    - name: "5300"
      port: 5300
      targetPort: 53
    - name: 5300-udp
      port: 5300
      protocol: UDP
      targetPort: 53
  selector:
    io.kompose.service: dns
