apiVersion: v1
data:
  named.conf.options: |-
    options {
        directory "/var/cache/bind";

        // Reenvía lo que no sabe resolver a Google/Cloudflare
        forwarders {
            8.8.8.8;
            1.1.1.1;
        };

        forward only;
        dnssec-validation no;
        listen-on { any; };
        allow-query { any; };
    };
kind: ConfigMap
metadata:
  annotations:
    use-subpath: "true"
  labels:
    io.kompose.service: dns
  name: dns-cm1
