apiVersion: v1
data:
  ca.crt: |
    -----BEGIN CERTIFICATE-----
    MIIFZTCCA02gAwIBAgIUZNKM50FSOFIO0z1LuBWBEN37urgwDQYJKoZIhvcNAQEL
    BQAwQjELMAkGA1UEBhMCQ1IxEDAOBgNVBAgMB1Nhbkpvc2UxEjAQBgNVBAoMCVRF
    Qy1SZWRlczENMAsGA1UEAwwETWlDQTAeFw0yNjA2MTMxODA3NDVaFw0zNjA2MTAx
    ODA3NDVaMEIxCzAJBgNVBAYTAkNSMRAwDgYDVQQIDAdTYW5Kb3NlMRIwEAYDVQQK
    DAlURUMtUmVkZXMxDTALBgNVBAMMBE1pQ0EwggIiMA0GCSqGSIb3DQEBAQUAA4IC
    DwAwggIKAoICAQDCNs0VFyRqrdIVcYIXgJVzsaSG2Kqg4S2DR/I/lQ08HiQx/pfA
    hKXjGP1tWCiH3I2FwDqtykgLd+dc63NztGq54a5GkvkltnsEf+NCU6kve6v16pdc
    Qc/eLLDJKDRoJ6qMwkV2mR9rmysv3i/0xXl3Jw0v7cdo2DY04bc1dcsRtyww09Mb
    I7ZVDOSkEcOanHgWTVf/gsTsm/9jzRF/U+aFwXrKZ0ZN6TIXy8gpvLNCcld6GD3I
    M28aTq9/sSo4pm7pA85WuFH27LKnkFxan2ib+wJDIddDzmBmPZPFZGOLkdsvBIca
    vcFANO7un0/XuVE/hW65FZxbRw4lJMfMYHIPdn3SivOOTZUks8wzbQ51p/rNFv9s
    QzLqJ+ZlqRGpAK91yxXYxIQPNYyjMvkpqAXNBAP4R/DwHqLAiZnU0j56nvhRxQ4V
    4BzC16L7PR9P0jAllAj1t/AQLaS7n4dd43et8A2kMu1iEdg8DkwAVBMCoWz+IvvQ
    +ueSeM1uwg3Z5FCImI3qjigxhJA0xnSvDJ3CefJu3F7wyxWiHMpE9hcFnPko5rH2
    7ExA4mLgcHg94HX2eCc4VE6QKvtx9N0awMdn78wQswaAI1JIviyM7pLPtJS6dPbr
    VUnguynf0xgEN4SDBgJjI6CVduEqkDhXcWmvZdPghYdLbGrMf7q3RQ2RzwIDAQAB
    o1MwUTAdBgNVHQ4EFgQURx3niwHDitsH1B9lwHrAFq2KUhEwHwYDVR0jBBgwFoAU
    Rx3niwHDitsH1B9lwHrAFq2KUhEwDwYDVR0TAQH/BAUwAwEB/zANBgkqhkiG9w0B
    AQsFAAOCAgEArCRtZAQU8N2ZknjqOtr7rJmUh946hhKx9qLKvt5ydU++Y2TDaLHI
    986g0Hp6YUaL3kNPo1Uqmo4v4YQ+qWKf45DQEVxxGh1PjI01HwycW8rZq3mv/0wG
    Rp5ZYCMHI5o9y6Apoq8q/kMQ1OD+gX5zTvXpvoVOWBvZWyIxMGIeRhW02fVUkfba
    jGk+OSAJRQ08HF5f0vX0sFcsOaoN2FIg4rc9g2DJyC4i2NXPe54d8VL/kZTtlTdd
    pikGjNMDSEC6gA3oSVOn7RmhzHOqP6HhHTmAp2q4CLTiuEZpz4lPDh/k0oof3CPv
    eE5w83CSZWqe8mBNSbbDDen0PbML2wxrXs0zzfRype7RrJIzSOPPBHwwdVM+4sHf
    jYNI/XWECZnyghlpReg4ieJrH4CsxHX+4SmlMMIxWdpSPowhx+5BRfhRaVgRt3i1
    cgFpQmecbqk7S5fxu0bGSKsZ39Jh4fw6iTeMQs4EPkyIJGSHZaba1PI9Cvp537BY
    UddlVhf3e1Qrd1pME9tpoWs3s/7GabQgZE/UoIjgh8o1O8NQV8BfDaL1pLz3KbrU
    3HAYgT+W1x4BsUPmCKnlzUCVIe68Y7LvA7+UXTxYUNIjwbvsob4dmSNtsNsU/ChQ
    2jdN4blDDujCwIEgog+Iv6vD27o3gv46yXoljiM9WIu3etBI1t6l8rg=
    -----END CERTIFICATE-----
  ca.key: |
    -----BEGIN PRIVATE KEY-----
    MIIJQwIBADANBgkqhkiG9w0BAQEFAASCCS0wggkpAgEAAoICAQDCNs0VFyRqrdIV
    cYIXgJVzsaSG2Kqg4S2DR/I/lQ08HiQx/pfAhKXjGP1tWCiH3I2FwDqtykgLd+dc
    63NztGq54a5GkvkltnsEf+NCU6kve6v16pdcQc/eLLDJKDRoJ6qMwkV2mR9rmysv
    3i/0xXl3Jw0v7cdo2DY04bc1dcsRtyww09MbI7ZVDOSkEcOanHgWTVf/gsTsm/9j
    zRF/U+aFwXrKZ0ZN6TIXy8gpvLNCcld6GD3IM28aTq9/sSo4pm7pA85WuFH27LKn
    kFxan2ib+wJDIddDzmBmPZPFZGOLkdsvBIcavcFANO7un0/XuVE/hW65FZxbRw4l
    JMfMYHIPdn3SivOOTZUks8wzbQ51p/rNFv9sQzLqJ+ZlqRGpAK91yxXYxIQPNYyj
    MvkpqAXNBAP4R/DwHqLAiZnU0j56nvhRxQ4V4BzC16L7PR9P0jAllAj1t/AQLaS7
    n4dd43et8A2kMu1iEdg8DkwAVBMCoWz+IvvQ+ueSeM1uwg3Z5FCImI3qjigxhJA0
    xnSvDJ3CefJu3F7wyxWiHMpE9hcFnPko5rH27ExA4mLgcHg94HX2eCc4VE6QKvtx
    9N0awMdn78wQswaAI1JIviyM7pLPtJS6dPbrVUnguynf0xgEN4SDBgJjI6CVduEq
    kDhXcWmvZdPghYdLbGrMf7q3RQ2RzwIDAQABAoICAB3yyWkpKmpw52Z7HG53W5R9
    njtVCerJDnWiEI8RcvsEQtyav9fmHJaKcfn8kDNzJTeszt+hw75Q/RJtFF6RQavs
    Sy2C2HyiSRIGjorZz8sMrRW82R5W37EI/zHlyz8MbtZJ1uBU+G1lfiFhh8+c7AAd
    u4Daj9dxD9rTu6a4xVmz/1KAN5uFxEYVOOS8AIfE/RejUaCLD8bUv2sqYjpaO8AA
    d+jiSAsXnKvitrkI6jOi4i5nso8+rzFFVPbB4RrfP1cbSSRCRBFpqpsAPd2Tm1QC
    PvUPMNy55E+fyzuzIU6SbVQwxIyxGi3Ge9m8I1nGr+q1rr9Hv9arfFjp9Q1lCfFn
    sLHYHsg6UKk8sjdghhpoQvB+AOW/GraeKRholznNu+amlD3ioX66iBe8YyV4wqB/
    EXk5N50ircPmObl1Jevn6DSsgWLjUzs8h4kP+olIs4+/EbpbQ/yvST4DpUMxwbY0
    DKd6OIFtWu2/bmNoX3uXZ91bUv+6p9X6g4YsKX66sW1L0jEsCIGCeSDfjDtL9LIF
    rUaTVKaMY9I9/DwCoVyDlb7QZq5p3lYbcYht2FY/OAqm1gtIHl7885jFdqTFvWav
    YJex9x4DPUGfh3EBhpmJCikyqgSO+XBksqzHuxsJjOFwEYTNzp0vyEEdC2+gkwwi
    unY6sB5VllEd5p56JVXRAoIBAQDkPiy/gtmbrQ2Rlf33SYxiRdPczloU3F8AHvmX
    UTIJ+svPQtbfUwWlhL1KEmGjiYNAXs5uYi9AexIWAkCRhbEnviUW0AX6ALurJT1x
    ykqibOvB4EloQWPlR035rx92cCk5XOMEEU3cRvmiqsy4jWWLBQay8wLfem2HywP3
    TC/rkPFZ/D5dWhMy8qEv220YIhgfbxuLLc95uj+Yn7xcb1aikI/i+y82it3YoASf
    wZoPA/43i70Eo7HpU4DlbpOsGEVXLProas7R5hgL/X75yC5Arsuhj6ImPpsmVnrv
    OKwy2OOk05tgN9x4JApwcHE3vRp56pLNSFtXSADuCYZiFCfDAoIBAQDZ1TduGmsA
    0SbBDdQeIqowCitpEgVc/KysETlDKFBVjeWnCuB8fKSKPAYEl39RipgL1zYKx+Rt
    AHQjgOPfdvL2ilv7WZZkGvMrAJ068+sDXERxtbu9ARpXT/g9PnXgQ8H4ocU2w3c1
    ThpjN1hrknugoOR1piM6zDj+wG/D0vfV/VlnapYYi7X6nG2F9AY392KOAR1/aojL
    v9Vfxy8BlKfpewdnyUBgELnHWeNhPElYZ29jsvx/Zpjdh/r2nyh7umwWo3czw5Ch
    o/+8VxCQ8d4a/grfR0lcfSClAsb2nuGNNY2Fr78EBOQzV1IlcPHTrCiPId6wIYcD
    1+XBoEKMclkFAoIBADw8bHLeha+gLESP4UayEmqdIxzTGNMIlcniYtycgShBGCjK
    6wplTsgwEATMdRhD4m/KlZBsOSw7TrqgPYoqTma+t+sdW3ZvWxf/7Adr6+aR+GZi
    Wv04xLRt7RZIMXWAhGCvMvqP1oyb7qYPjZfnOTVHTk1L9SYlmWKNIa7SXJM+3XNy
    LsNUUlzPy9plfpUv6k3hdNN2c5scnEwbXArJF4QvwsmUoREz9PiGwrGm1pG/7Aec
    yXW//eQmNY5XcIGqpiIrrMxJ4+thXldLv4cMXaiUeQlabuDJBQlJKYiY3FlPBEUr
    04XBOF48pMSn6Dldnu8uCTBEOFcAmb44pU6dIyECggEBAIGx/SrE9+ionpZbEWxP
    31xy8Z3BaQgQOQ7JwnpFym7l6VInm7kCzUSwsDSTru5xwk1qeXa5xTtRBdUNrJ8k
    R0ya3GEu2egIU7fKydKL3+VETkwVlA3YVkKeDoMIaU55iUfrqWwNvTAzrGpeTXre
    4FSm9t9FZ7xeU6D6GpFRTtZN3alBQNSkelkYQe17eShhVoCOEW4HlCMbuIMqKMac
    J81Pvv0ASh/oVXRoBIWkS1cjXqLRspx4DZP4nmewI35nZGumMBbV3YsgBeexPt/N
    4hvYHckKvJcguQsGOEgmGMzmkbiDBwvxjZ0z5Gj+cj1BR3TRCbF8hNK4/MboEDdm
    7bECggEBAIEQsfhzEvN66jTeuKqpEFQa/eP6eU2JxdvmbOJ/0ztgoE/ZLkPqJynT
    7+tYgvdwfxxmvLEFs54j9y2ZJ3rL4dIABVve2fQmrhaORs8uGqp4jAPecDAsVtsw
    NhMdLjQ5vOy5glsAd5fYYWfVsDoPSneiGPTyMyVh/NHo8EEAq0Y+hG0ip1N6r2YE
    qoTjzzkX78fgEKWvbKTZ5S21DCwYkYY0YmR8M/EKXWnyG1e6CDt9IT2hSr3tu3WJ
    bq3hv8Z0jURWAoItRpMWr5bhRxujX5A/rWUqE7Koyw8PiEo60UBlwRI56Xk/u2IQ
    C2R/CnxYl4uVLHuvSjtI6aBEzy63vTs=
    -----END PRIVATE KEY-----
  ca.srl: |
    62845FAB8D19341F427B25E52FE13B4B82F2991F
  server.crt: |
    -----BEGIN CERTIFICATE-----
    MIIEEDCCAfgCFGKEX6uNGTQfQnsl5S/hO0uC8pkfMA0GCSqGSIb3DQEBCwUAMEIx
    CzAJBgNVBAYTAkNSMRAwDgYDVQQIDAdTYW5Kb3NlMRIwEAYDVQQKDAlURUMtUmVk
    ZXMxDTALBgNVBAMMBE1pQ0EwHhcNMjYwNjEzMTgwNzQ1WhcNMjcwNjEzMTgwNzQ1
    WjBHMQswCQYDVQQGEwJDUjEQMA4GA1UECAwHU2FuSm9zZTESMBAGA1UECgwJVEVD
    LVJlZGVzMRIwEAYDVQQDDAlsb2NhbGhvc3QwggEiMA0GCSqGSIb3DQEBAQUAA4IB
    DwAwggEKAoIBAQDDxdfPEWpFBLEUxInPgy1OSNC6QFjz77KJNQcMilonZdZa39Y1
    JfEjLS/WsD/m6ENIwSqc+wWHZf5IqLkH31U91t9gOVm+LLDWKY50rV5Fgc3gSNES
    K8J4g6LQVyEBW10rNGgu+cI3gTn4mTT8kBCEZcQ2Ssk1a8l8cDeZ4WcET7+Hxah7
    JEJY9eDIt8ZR0IyY6r2kHaXFJDcwK3NyyW/dcIiRYZCM7KqLfXvgBhAu0tkYRGdI
    I/zYI2mCFe6qbyig5haqZyupTFiArhWoHbiKaDEK4tJlqhxSzM8P5taiZsy6pjpA
    BMciyYQyU1n2+J6AErMUJRyEWllazLJAXj+3AgMBAAEwDQYJKoZIhvcNAQELBQAD
    ggIBAA24YJl5D8OpWg0SKTRMb/X5LW5ryEkIji3jJf7VjnavBFzE5giaavIb63YL
    YO9qV5PX9sRrf06VIc9dmta9C+RztzFTsKNfaGjcE83grOGbA2/piWAJj8jmzmJc
    OYWzwWF6adv+vVvjtUp7vP2nOWEExZxaJDf2N0AvzFa7x897CtRgynITHSetqnKb
    fpccyLRmOJU9EKT4Cna3bPFUfAcOLqz62QLhfhvMuMRLMtUUNgPO0KUy3QPpjkUB
    4VUUi0ZKpQ6VHtpoJc/djuoFhINxj+qYgYzoOCQeUf6et6mPUBk5ZE5Yxbu6wESb
    O/YRnp8Dhu0njJSK2Jmaj0mbl2Bz6D5oApPqAZusi6KYi0X+DlwmvwU8UuIrsWOJ
    dAcUSl8HGwy9rk4NcZjQcAmcbLLYQR2FmR8KvDVOKpF2slbZfIiT5g1sdSelKepC
    z4fcvIHnu8/NImLXtuTDbz85jLoO5lA+YxrsJlWAhHZg6WhZAQUyn1KpxsTv2DiT
    Kvy9sjt3KfJKyXNFXaoN94Whc6SZXmnEUu3OL7IoE7W6wz9NfQCbMh5j49jKX8Kf
    U3dbJjM0M78/NFebrtjV8/RuZr1epGv8+1i5lpERCMLc9WuCmPCMnBrKttb3kYXy
    tQy3hcQO4cI0Xd08VLawLWgTVNUrLQ9KhyeUN8+HnvPmsRLa
    -----END CERTIFICATE-----
  server.csr: |
    -----BEGIN CERTIFICATE REQUEST-----
    MIICjDCCAXQCAQAwRzELMAkGA1UEBhMCQ1IxEDAOBgNVBAgMB1Nhbkpvc2UxEjAQ
    BgNVBAoMCVRFQy1SZWRlczESMBAGA1UEAwwJbG9jYWxob3N0MIIBIjANBgkqhkiG
    9w0BAQEFAAOCAQ8AMIIBCgKCAQEAw8XXzxFqRQSxFMSJz4MtTkjQukBY8++yiTUH
    DIpaJ2XWWt/WNSXxIy0v1rA/5uhDSMEqnPsFh2X+SKi5B99VPdbfYDlZviyw1imO
    dK1eRYHN4EjREivCeIOi0FchAVtdKzRoLvnCN4E5+Jk0/JAQhGXENkrJNWvJfHA3
    meFnBE+/h8WoeyRCWPXgyLfGUdCMmOq9pB2lxSQ3MCtzcslv3XCIkWGQjOyqi317
    4AYQLtLZGERnSCP82CNpghXuqm8ooOYWqmcrqUxYgK4VqB24imgxCuLSZaocUszP
    D+bWombMuqY6QATHIsmEMlNZ9viegBKzFCUchFpZWsyyQF4/twIDAQABoAAwDQYJ
    KoZIhvcNAQELBQADggEBAEODpmhCg1sLH1Jx3fO0ShjVl2c+g6SuYitZLhQEeV9W
    F2r4DpS3YlM7GB4T1kZTcB1r7to775zya2iSV6JIHAPX3y70S9NH9tEVE4jy9NS/
    cgPRp0nCcfQiXftuPWUqCuYCwMEl0DhpM0qHUra7QA8ShrepFCPoqRU4ccMh5AB5
    9UlDbGMfoIDJNMGZnXtkF8SUATxTGk0JOGskTKYsvM0xnx/YlgT43IyxAreYNRgH
    WY7yOlPNCohG2KaEdMLnEKz9HWLyRxL2cD9/iCGl2uYplrcobYcgniim64dtv/2e
    zWq39F0ERGjFP2Lo1QUV4CVVQway/oiEYIcZyb+BWZE=
    -----END CERTIFICATE REQUEST-----
  server.key: |
    -----BEGIN PRIVATE KEY-----
    MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDDxdfPEWpFBLEU
    xInPgy1OSNC6QFjz77KJNQcMilonZdZa39Y1JfEjLS/WsD/m6ENIwSqc+wWHZf5I
    qLkH31U91t9gOVm+LLDWKY50rV5Fgc3gSNESK8J4g6LQVyEBW10rNGgu+cI3gTn4
    mTT8kBCEZcQ2Ssk1a8l8cDeZ4WcET7+Hxah7JEJY9eDIt8ZR0IyY6r2kHaXFJDcw
    K3NyyW/dcIiRYZCM7KqLfXvgBhAu0tkYRGdII/zYI2mCFe6qbyig5haqZyupTFiA
    rhWoHbiKaDEK4tJlqhxSzM8P5taiZsy6pjpABMciyYQyU1n2+J6AErMUJRyEWlla
    zLJAXj+3AgMBAAECggEASYSrdXxhvwdzBIyGACKPyf04PSla/kg+cJ40RnZSQsdQ
    hxHV3GGiO4aFl4baiHkig1jfCtKNkfowUtLhoV4yIaXmfrkqxWr9AX/bml9crpd/
    W8GcmclLH3y3kKuXnm3UAByPH0z1rWhe/8dxCYOEYGPjGkxdYS1YHd36U1Q9HnW3
    /RaACgt+TmYpjnIump5Wu29qgYixnS0VGCKn4ICRSGDY9nesilfEC6li9xbd5dmY
    ANvkhVOzEowQ2Dcs2AP9hwkfXNtPs+P8LXgXPmBKZV+yQopkkidV9uOFKJCuLors
    vE//s+j0E6nMGIQOtO0Q2KPeMDxN2SdC3/j1CM/LAQKBgQDpFVk1ISMpbaSxUqaZ
    VDkAJ+nn3YSAonjB74tRUlHlUC5j5ZgMVGv5rPJrO1YHgOz5nHdGBIcaz3FYAy0h
    nYK+sXpsx5bVkdx6+CU4FNJPszdmsAXGZiOdNw5FCW7q5Z+VX9X1kY8l6e3m8/Jw
    V5NZHRNLuoLbzH4rtcBJzkFdgQKBgQDXBWWQMLQRZlhqRwBdpwyWK2R8RLKjckyR
    yvkHBJiEb6HuLCZaWmOFIq5na8flWN46qVoiLVxoebCBBX+t4nGtPCX054TSzBl/
    gZqtLlweBgd3uwWU7CXPYIwpmWVzJXts6VJajBBrfXhExcx3JoHziZ9qzW64nZgh
    C69vqBmpNwKBgDCipsGiT372hPYHRAIcg+RXb8RVAbABtubowA5Q+gu6ZmOr5cU0
    3G71uoPLltDsAwa2smCm0zYx8PmneARapIx75grKvtuDmxkBrGp+VcARqk7ADgRv
    DaFhepXHOSDElz8JB1E9dTw5Cs41OvJcI7/lhEA6A9IvYmhmfWApLJSBAoGAB4KP
    vo6E64qokeWy9JJuFRyk4NZBawYF+J2fPwiBDzca78eo+0Tm7vJ8Ju6Tx8Xn1SKv
    HDx7WsbNTGRVxkv/bm6IYNppQDeSuGpdbakN3JqXTi5BDqeE1o5nttg9u9zWR8KK
    dtEnjamPNs+1yX+V0FzBLajJMjeG5biTwxGa+9cCgYEAxmvCRlh3DgLwhimyVMKl
    UVLuy2Y6XH6OAhpKWhj+b5inqv25jJa0JDjCZx9aHoDOwG9V8R+eRCdTvdWl8eaG
    9z2klVJUOEptafB1nmu6CYcEMfJPY1OTzkApCJl/USQxM9YPfsnUOa2KPty196+D
    Mq3vYehCAqa+d1CJ5/ZCwAs=
    -----END PRIVATE KEY-----
kind: ConfigMap
metadata:
  labels:
    io.kompose.service: nginx
  name: nginx-cm1
