# Copiar este archivo a inventory.ini y reemplazar con la IP pública
# que imprime "terraform output openvpn_public_ip"

[openvpn_server]
52.203.159.84 ansible_user=ubuntu ansible_ssh_private_key_file=/home/ariana/Downloads/paas-vpn.pem ansible_ssh_common_args='-o StrictHostKeyChecking=no'
